# Generated by Django 3.1 on 2020-12-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_acquired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquired',
            name='owned',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Yes', max_length=100),
        ),
    ]
