# Generated by Django 3.1 on 2020-12-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201228_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='collectors',
            field=models.ManyToManyField(to='main_app.Collector'),
        ),
    ]
